Update content alignment in trigger
AlaskaAirlines/auro-accordion pull request #49
Opened 2022-02-04 22:55 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #47 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

The scope of this commit is to update the treatment of content in the trigger slot of the accordion. This solution will provide
an initial opinion of alignment while allowing users to customize the space per their specific content needs.

<img width="695" alt="Screen Shot 2022-02-04 at 2 53 41 PM" src="https://user-images.githubusercontent.com/181089/152613838-39580968-a7b6-47ef-8415-63f49474de20.png">

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-02-07 19:41 UTC, jason-capsule42 requested changes
The accordion chevron is not aligning with the trigger content. There is currently no class on that div wrapping the chevron SVG.

We should add something like `.triggerChevron` and then do the same trick of making it flex and align-items: center.

2022-02-07 20:42 UTC, blackfalcon commented
Update added to the placement of the chevron in the trigger layout. 

<img width="447" alt="Screen Shot 2022-02-07 at 12 37 54 PM" src="https://user-images.githubusercontent.com/181089/152868736-a0cf20ac-17c7-412c-9a60-180cc6071d26.png">
<img width="436" alt="Screen Shot 2022-02-07 at 12 39 46 PM" src="https://user-images.githubusercontent.com/181089/152868739-5e1ac8e6-ff3f-40ad-86eb-6906c290b697.png">
<img width="438" alt="Screen Shot 2022-02-07 at 12 40 16 PM" src="https://user-images.githubusercontent.com/181089/152868740-330fd409-3ae5-445a-a053-63362725545d.png">

2022-02-08 00:47 UTC, Luno89 submitted a review, later dismissed

2022-02-08 18:21 UTC, jason-capsule42 approved these changes

2022-02-08 18:55 UTC, merged